server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: 智学云在线学习平台

logging:
  level:
    cs.sbs.web: INFO
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
